export const auditEvents = {
  ACTIVE_COMPANY_CHANGED: "ACTIVE_COMPANY_CHANGED",
  COMPANY_ACCESS_DENIED: "COMPANY_ACCESS_DENIED",
  PASSWORD_VIEWED: "PASSWORD_VIEWED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
} as const;

export type AuditEvent = keyof typeof auditEvents;
